#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : powertop
Version  : 2.8
Release  : 17
URL      : https://github.com/fenrus75/powertop/archive/v2.8.tar.gz
Source0  : https://github.com/fenrus75/powertop/archive/v2.8.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: powertop-bin
Requires: powertop-locales
Requires: powertop-doc
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(libpci)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
Patch1: no-intel.patch

%description
ï»¿Building & Installing PowerTOP
------------------------------
To build and install PowerTOP type the following commands,
./configure
./make
./make install

%package bin
Summary: bin components for the powertop package.
Group: Binaries

%description bin
bin components for the powertop package.


%package doc
Summary: doc components for the powertop package.
Group: Documentation

%description doc
doc components for the powertop package.


%package locales
Summary: locales components for the powertop package.
Group: Default

%description locales
locales components for the powertop package.


%prep
%setup -q -n powertop-2.8
%patch1 -p1

%build
%autogen --disable-static
make V=1  %{?_smp_mflags}

%check
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
rm -rf %{buildroot}
%make_install
%find_lang powertop

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/powertop

%files doc
%defattr(-,root,root,-)
%doc /usr/share/man/man8/*

%files locales -f powertop.lang 
%defattr(-,root,root,-)

