#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : powertop
Version  : 2.13
Release  : 29
URL      : https://01.org/sites/default/files/downloads/powertop-2.13.tar.gz
Source0  : https://01.org/sites/default/files/downloads/powertop-2.13.tar.gz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-2.0
Requires: powertop-bin = %{version}-%{release}
Requires: powertop-data = %{version}-%{release}
Requires: powertop-license = %{version}-%{release}
Requires: powertop-locales = %{version}-%{release}
Requires: powertop-man = %{version}-%{release}
BuildRequires : gettext
BuildRequires : perl(XML::Parser)
BuildRequires : pkgconfig(libnl-3.0)
BuildRequires : pkgconfig(libnl-genl-3.0)
BuildRequires : pkgconfig(libpci)
BuildRequires : pkgconfig(ncurses)
BuildRequires : pkgconfig(ncursesw)
Patch1: no-intel.patch

%description
﻿# PowerTOP
PowerTOP is a Linux* tool used to diagnose issues with power consumption and
power management. In addition to being a diagnostic tool, PowerTOP also has an
interactive mode you can use to experiment with various power management
settings, for cases where the Linux distribution has not enabled those
settings.

%package bin
Summary: bin components for the powertop package.
Group: Binaries
Requires: powertop-data = %{version}-%{release}
Requires: powertop-license = %{version}-%{release}

%description bin
bin components for the powertop package.


%package data
Summary: data components for the powertop package.
Group: Data

%description data
data components for the powertop package.


%package license
Summary: license components for the powertop package.
Group: Default

%description license
license components for the powertop package.


%package locales
Summary: locales components for the powertop package.
Group: Default

%description locales
locales components for the powertop package.


%package man
Summary: man components for the powertop package.
Group: Default

%description man
man components for the powertop package.


%prep
%setup -q -n powertop-2.13
cd %{_builddir}/powertop-2.13
%patch1 -p1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1591982369
export GCC_IGNORE_WERROR=1
export CFLAGS="$CFLAGS -fno-lto "
export FCFLAGS="$FFLAGS -fno-lto "
export FFLAGS="$FFLAGS -fno-lto "
export CXXFLAGS="$CXXFLAGS -fno-lto "
%configure --disable-static
make  %{?_smp_mflags}

%check
export LANG=C.UTF-8
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
make VERBOSE=1 V=1 %{?_smp_mflags} check

%install
export SOURCE_DATE_EPOCH=1591982369
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/powertop
cp %{_builddir}/powertop-2.13/COPYING %{buildroot}/usr/share/package-licenses/powertop/a7a897a4bde987e597c04f16a9c28f6d3f57916d
%make_install
%find_lang powertop

%files
%defattr(-,root,root,-)

%files bin
%defattr(-,root,root,-)
/usr/bin/powertop

%files data
%defattr(-,root,root,-)
/usr/share/bash-completion/completions/powertop

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/powertop/a7a897a4bde987e597c04f16a9c28f6d3f57916d

%files man
%defattr(0644,root,root,0755)
/usr/share/man/man8/powertop.8

%files locales -f powertop.lang
%defattr(-,root,root,-)

